export const pokemon = [
  {
    name: "Charmander",
    type: "fire",
    level: 5,
    attack: 10,
    spAttack: 100,
    spDefense: 100,
    defense: 100,
    speed: 100,
    hp: 39,
    img: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png",
    attacks: [
      {
        name: "Scratch",
        target: "attack",
        damage: 4,
        others: "none",
        type: "normal",
        accuracy: 100,
      },
      {
        name: "Ember",
        target: "attack",
        damage: 6,
        others: "burn",
        type: "fire",
        accuracy: 100,
      },
      {
        name: "Growl",
        target: "stats",
        damage: 0,
        others: "none",
        type: "normal",
        accuracy: 100,
      },
      {
        name: "Tackle",
        target: "attack",
        damage: 3,
        others: "none",
        type: "normal",
      },
    ],
  },
  {
    name: "Bulbasaur",
    type: "grass",
    level: 5,
    hp: 43,
    img: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png",
    attacks: [
      {
        name: "Scratch",
        target: "attack",
        damage: 4,
        others: "none",
        type: "normal",
      },
      {
        name: "Absorb",
        target: "attack",
        damage: 6,
        others: "recover",
        type: "grass",
      },
      {
        name: "Growl",
        target: "stats",
        damage: 0,
        others: "none",
        type: "normal",
      },
      {
        name: "Tackle",
        target: "attack",
        damage: 3,
        others: "none",
        type: "normal",
      },
    ],
  },
];
